# Docker compose syntax to use to avoid breaking changes.
version: "3.9"

services:
    app:
        build:
            context: . # Use current directory.
            args:
                - DEV=true # From our Dockerfile to install requirements.dev
        ports:
            - "8000:8000" # Access
        volumes:
            - ./app:/app # Map directory in our system to our container. To sync local changes to our container without the need to rebuild.
        command: > # Runs our django app
            sh -c "python manage.py wait_for_db && 
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment: # We use and pull the below environment variables through settings.py
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASSWORD=changeme
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changeme

volumes:
    dev-db-data:
