name: Checks
on: [push]
jobs:
    test-lint:
        name: Test & Lint
        runs-on: ubuntu-20.04
        steps:
            - name: Login to docker hub
              uses: docker/login-action@v1
              with:
                  username: ${{secrets.DOCKERHUB_USER}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}
                  
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                path: /tmp/.docker-cache
                key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile', '**/requirements*.txt') }}
                restore-keys: |
                  ${{ runner.os }}-docker-
                  
            - name: Build
              run: |
                docker compose build --build-arg DEV=true
                
            - name: Test
              run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
              
            - name: Lint
              run: docker compose run --rm app sh -c "flake8"
