name: Checks

on:
  push:
    branches:
      - "**"  # Runs on all branches

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Compose
        run: docker compose build

  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    needs: setup  # Ensure setup job runs before this
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

  lint:
    name: Run Lint
    runs-on: ubuntu-20.04
    needs: setup  # Ensure setup job runs before this
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Linting
        run: docker compose run --rm app sh -c "flake8"
